'use client'
import { Header } from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import {NextUIProvider} from "@nextui-org/react";
import Footer from "@/components/Footer";
import localFont from 'next/font/local'

const mona = localFont({
  src: '../fonts/Mona-Sans.ttf',
  display: 'swap',
  variable: '--font-mona',
})
const dmserif = localFont({
  src: '../fonts/Dmserif.ttf',
  display: 'swap',
  variable: '--font-dmserif',
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${mona.variable} ${dmserif.variable}`}>
      <body className={mona.className}>
      <NextUIProvider>
        <Header />
        {children}
        <Footer/>
        </NextUIProvider>
      </body>
    </html>
  );
}
